### ISSUE TITLE
Readme Issues

### ISSUE THREAD

**Issue by tahege** [ITNG/labsite#29]
In Local Development where we need to install the apps manually, immediately following 
$ pip install git+git://github.com/ITNG/foodapp.git
we are told to run
$ pip install -Ur path/to/worklog/requirements.txt
What is this?

**Comment by dralley** [comment]
pip install -r [file] will treat the file like it's a list of packages to
be installed.

So if you've got the following in some text file (like requirements.txt)

django
>
numpy
>
flask
>

It'll go through the list and install all of them at the same time instead
of having to type pip install [X] for all of them manually

**Comment by tahege** [comment]
Sorry I was unclear before. 

I meant what is this path supposed to be, because there is no path/to/worklog/requirements.txt at this point in the setup.

If we're supposed to have cloned worklog at this point and we're supposed to pip install the requirements.txt from there, then this needs to be made clear.

So either this path/file is not in the directory so we need to determine why it's not, or this was just a placeholder (my guess) for the actual path.

**Comment by dralley** [comment]
It's just a placeholder.
