### ISSUE TITLE
Small screen size covers up content

### ISSUE THREAD

**Issue by mbrown1413** [ITNG/labsite#65]
On worklog there are nav items that will cover up content. This probably applies to other apps as well. See the screneshot:

![screenshot_2018-03-06_10-45-46](https://user-images.githubusercontent.com/186278/37042122-c6069616-212b-11e8-842d-644ca1d4a73f.png)

Note that in the screenshot, I haven't expanded the hamburger menu. Doing so hides even more content.

**Comment by rpkilby** [comment]
The nav links are now located in the collapsable section.
